apiVersion: v1
kind: Namespace
metadata:
  name: regulated-services
  labels:
    app.kubernetes.io/part-of: clustershield360
    environment-tier: regulated
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
