apiVersion: v1
kind: ServiceAccount
metadata:
  name: patient-api-sa
  namespace: regulated-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workload-reader
  namespace: regulated-services
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - pods
      - services
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workload-reader-binding
  namespace: regulated-services
subjects:
  - kind: ServiceAccount
    name: patient-api-sa
    namespace: regulated-services
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workload-reader
